In [1]:
!pip install pandas numpy matplotlib scikit-learn flask joblib

Requirement already satisfied: pandas in c:\users\faisal\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\users\faisal\anaconda3\lib\site-packages (2.3.5)
Requirement already satisfied: matplotlib in c:\users\faisal\anaconda3\lib\site-packages (3.10.6)
Requirement already satisfied: scikit-learn in c:\users\faisal\anaconda3\lib\site-packages (1.7.2)
Requirement already satisfied: flask in c:\users\faisal\anaconda3\lib\site-packages (3.1.2)
Requirement already satisfied: joblib in c:\users\faisal\anaconda3\lib\site-packages (1.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\faisal\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\faisal\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\faisal\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\faisal\anaconda3\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\faisal\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\faisal\anaconda3\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\faisal\anaconda3\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\faisal\anaconda3\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\faisal\anaconda3\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\faisal\anaconda3\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: scipy>=1.8.0 in c:\users\faisal\anaconda3\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\faisal\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: blinker>=1.9.0 in c:\users\faisal\anaconda3\lib\site-packages (from flask) (1.9.0)
Requirement already satisfied: click>=8.1.3 in c:\users\faisal\anaconda3\lib\site-packages (from flask) (8.2.1)
Requirement already satisfied: itsdangerous>=2.2.0 in c:\users\faisal\anaconda3\lib\site-packages (from flask) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in c:\users\faisal\anaconda3\lib\site-packages (from flask) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in c:\users\faisal\anaconda3\lib\site-packages (from flask) (3.0.2)
Requirement already satisfied: werkzeug>=3.1.0 in c:\users\faisal\anaconda3\lib\site-packages (from flask) (3.1.3)
Requirement already satisfied: colorama in c:\users\faisal\anaconda3\lib\site-packages (from click>=8.1.3->flask) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\users\faisal\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
!pip install pandas numpy matplotlib seaborn scikit-learn flask joblib

Requirement already satisfied: pandas in c:\users\faisal\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\users\faisal\anaconda3\lib\site-packages (2.3.5)
Requirement already satisfied: matplotlib in c:\users\faisal\anaconda3\lib\site-packages (3.10.6)
Requirement already satisfied: seaborn in c:\users\faisal\anaconda3\lib\site-packages (0.13.2)
Requirement already satisfied: scikit-learn in c:\users\faisal\anaconda3\lib\site-packages (1.7.2)
Requirement already satisfied: flask in c:\users\faisal\anaconda3\lib\site-packages (3.1.2)
Requirement already satisfied: joblib in c:\users\faisal\anaconda3\lib\site-packages (1.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\faisal\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\faisal\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\faisal\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\faisal\anaconda3\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\faisal\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\faisal\anaconda3\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\faisal\anaconda3\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\faisal\anaconda3\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\faisal\anaconda3\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\faisal\anaconda3\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: scipy>=1.8.0 in c:\users\faisal\anaconda3\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\faisal\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: blinker>=1.9.0 in c:\users\faisal\anaconda3\lib\site-packages (from flask) (1.9.0)
Requirement already satisfied: click>=8.1.3 in c:\users\faisal\anaconda3\lib\site-packages (from flask) (8.2.1)
Requirement already satisfied: itsdangerous>=2.2.0 in c:\users\faisal\anaconda3\lib\site-packages (from flask) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in c:\users\faisal\anaconda3\lib\site-packages (from flask) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in c:\users\faisal\anaconda3\lib\site-packages (from flask) (3.0.2)
Requirement already satisfied: werkzeug>=3.1.0 in c:\users\faisal\anaconda3\lib\site-packages (from flask) (3.1.3)
Requirement already satisfied: colorama in c:\users\faisal\anaconda3\lib\site-packages (from click>=8.1.3->flask) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\users\faisal\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier

import joblib

In [5]:
df = pd.read_csv("StudentPerformanceFactors.csv")

In [6]:
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [8]:
df.shape

(6607, 20)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   object
 3   Access_to_Resources         6607 non-null   object
 4   Extracurricular_Activities  6607 non-null   object
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   object
 8   Internet_Access             6607 non-null   object
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   object
 11  Teacher_Quality             6529 non-null   object
 12  School_Type                 6607 non-null   object
 13  Peer_Influence              6607 non-null   object
 14  Physical_Activity           6607 non-null   int64
 15  Learning_Disabilities       6607 non-null   object
 16  Parental_Education_Level    6517 non-null   object
 17  Distance_from_Home          6540 non-null   object
 18  Gender                      6607 non-null   object
 19  Exam_Score                  6607 non-null   int64
dtypes: int64(7), object(13)
memory usage: 1.0+ MB

In [10]:
df.describe()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score
count,6607.000000,6607.000000,6607.00000,6607.000000,6607.000000,6607.000000,6607.000000
mean,19.975329,79.977448,7.02906,75.070531,1.493719,2.967610,67.235659
std,5.990594,11.547475,1.46812,14.399784,1.230570,1.031231,3.890456
min,1.000000,60.000000,4.00000,50.000000,0.000000,0.000000,55.000000
25%,16.000000,70.000000,6.00000,63.000000,1.000000,2.000000,65.000000
50%,20.000000,80.000000,7.00000,75.000000,1.000000,3.000000,67.000000
75%,24.000000,90.000000,8.00000,88.000000,2.000000,4.000000,69.000000
max,44.000000,100.000000,10.00000,100.000000,8.000000,6.000000,101.000000

In [11]:
df.isnull().sum()

Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
dtype: int64

In [12]:
df.columns

Index(['Hours_Studied', 'Attendance', 'Parental_Involvement',
       'Access_to_Resources', 'Extracurricular_Activities', 'Sleep_Hours',
       'Previous_Scores', 'Motivation_Level', 'Internet_Access',
       'Tutoring_Sessions', 'Family_Income', 'Teacher_Quality', 'School_Type',
       'Peer_Influence', 'Physical_Activity', 'Learning_Disabilities',
       'Parental_Education_Level', 'Distance_from_Home', 'Gender',
       'Exam_Score'],
      dtype='object')

In [13]:
df.dtypes

Hours_Studied                  int64
Attendance                     int64
Parental_Involvement          object
Access_to_Resources           object
Extracurricular_Activities    object
Sleep_Hours                    int64
Previous_Scores                int64
Motivation_Level              object
Internet_Access               object
Tutoring_Sessions              int64
Family_Income                 object
Teacher_Quality               object
School_Type                   object
Peer_Influence                object
Physical_Activity              int64
Learning_Disabilities         object
Parental_Education_Level      object
Distance_from_Home            object
Gender                        object
Exam_Score                     int64
dtype: object

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df = df.drop_duplicates()

In [16]:
df["Exam_Score"].describe()

count    6607.000000
mean       67.235659
std         3.890456
min        55.000000
25%        65.000000
50%        67.000000
75%        69.000000
max       101.000000
Name: Exam_Score, dtype: float64

In [17]:
df["Result"] = df["Exam_Score"].apply(lambda x: 1 if x >= 50 else 0)

In [18]:
df["Result"].value_counts()

Result
1    6607
Name: count, dtype: int64

In [19]:
df = df.drop("Exam_Score", axis=1)

In [20]:
df.select_dtypes(include="object").columns

Index(['Parental_Involvement', 'Access_to_Resources',
       'Extracurricular_Activities', 'Motivation_Level', 'Internet_Access',
       'Family_Income', 'Teacher_Quality', 'School_Type', 'Peer_Influence',
       'Learning_Disabilities', 'Parental_Education_Level',
       'Distance_from_Home', 'Gender'],
      dtype='object')

In [36]:
from sklearn.preprocessing import LabelEncoder

encoders = {}

for col in df.select_dtypes(include="object").columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    encoders[col] = le

In [37]:
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Result
0,23,84,1,0,0,7,73,1,1,0,1,2,1,2,3,0,1,2,1,1
1,19,64,1,2,0,8,59,1,1,2,2,2,1,0,4,0,0,1,0,1
2,24,98,2,2,1,7,91,2,1,2,2,2,1,1,4,0,2,2,1,1
3,29,89,1,2,1,8,98,2,1,1,2,2,1,0,4,0,1,1,1,1
4,19,92,2,2,1,6,65,2,1,3,2,0,1,1,4,0,0,2,0,1

In [38]:
X = df.drop("Result", axis=1)
y = df["Result"]

In [39]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [40]:
print(X_train.shape)
print(X_test.shape)

(5285, 19)
(1322, 19)

In [41]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [42]:
y_pred = model.predict(X_test)

In [43]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 1.0

In [44]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00      1322

    accuracy                           1.00      1322
   macro avg       1.00      1.00      1.00      1322
weighted avg       1.00      1.00      1.00      1322

In [49]:
import joblib

joblib.dump(model, "model/student_model.pkl")

print("Model saved successfully!")

Model saved successfully!

In [50]:
X.columns.tolist()

['Hours_Studied',
 'Attendance',
 'Parental_Involvement',
 'Access_to_Resources',
 'Extracurricular_Activities',
 'Sleep_Hours',
 'Previous_Scores',
 'Motivation_Level',
 'Internet_Access',
 'Tutoring_Sessions',
 'Family_Income',
 'Teacher_Quality',
 'School_Type',
 'Peer_Influence',
 'Physical_Activity',
 'Learning_Disabilities',
 'Parental_Education_Level',
 'Distance_from_Home',
 'Gender']

In [51]:
df.select_dtypes(include="object").columns.tolist()

[]

In [52]:
original_df = pd.read_csv("StudentPerformanceFactors.csv")
original_df.select_dtypes(include="object").columns.tolist()

['Parental_Involvement',
 'Access_to_Resources',
 'Extracurricular_Activities',
 'Motivation_Level',
 'Internet_Access',
 'Family_Income',
 'Teacher_Quality',
 'School_Type',
 'Peer_Influence',
 'Learning_Disabilities',
 'Parental_Education_Level',
 'Distance_from_Home',
 'Gender']

In [53]:
joblib.dump(encoders, "model/encoders.pkl")

print("Encoders saved successfully!")

Encoders saved successfully!

In [55]:
for col in encoders:
    print(f"\n{col}:")
    print(encoders[col].classes_)

In [56]:
print(encoders)

{}

In [57]:
print(type(encoders))
print(len(encoders))

<class 'dict'>
0

In [58]:
encoders.keys()

dict_keys([])

In [59]:
df.select_dtypes(include="object").columns

Index([], dtype='object')

In [60]:
print(encoders)

{}

In [61]:
print(len(encoders))

0

In [62]:
original_df.select_dtypes(include="object").columns.tolist()

['Parental_Involvement',
 'Access_to_Resources',
 'Extracurricular_Activities',
 'Motivation_Level',
 'Internet_Access',
 'Family_Income',
 'Teacher_Quality',
 'School_Type',
 'Peer_Influence',
 'Learning_Disabilities',
 'Parental_Education_Level',
 'Distance_from_Home',
 'Gender']

In [63]:
df = pd.read_csv("StudentPerformanceFactors.csv")

In [64]:
from sklearn.preprocessing import LabelEncoder

encoders = {}

for col in df.select_dtypes(include="object").columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    encoders[col] = le

print("Encoders created successfully!")
print(encoders.keys())

Encoders created successfully!
dict_keys(['Parental_Involvement', 'Access_to_Resources', 'Extracurricular_Activities', 'Motivation_Level', 'Internet_Access', 'Family_Income', 'Teacher_Quality', 'School_Type', 'Peer_Influence', 'Learning_Disabilities', 'Parental_Education_Level', 'Distance_from_Home', 'Gender'])

In [65]:
df["Result"] = df["Exam_Score"].apply(lambda x: 1 if x >= 50 else 0)

In [66]:
df = df.drop("Exam_Score", axis=1)

In [67]:
X = df.drop("Result", axis=1)
y = df["Result"]

In [68]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [69]:
import joblib

joblib.dump(model, "model/student_model.pkl")
joblib.dump(encoders, "model/encoders.pkl")

print("Model and encoders saved successfully!")

Model and encoders saved successfully!

In [70]:
print(len(encoders))

13

In [71]:
for col in encoders:
    print(f"\n{col}:")
    print(encoders[col].classes_)

Parental_Involvement:
['High' 'Low' 'Medium']

Access_to_Resources:
['High' 'Low' 'Medium']

Extracurricular_Activities:
['No' 'Yes']

Motivation_Level:
['High' 'Low' 'Medium']

Internet_Access:
['No' 'Yes']

Family_Income:
['High' 'Low' 'Medium']

Teacher_Quality:
['High' 'Low' 'Medium' nan]

School_Type:
['Private' 'Public']

Peer_Influence:
['Negative' 'Neutral' 'Positive']

Learning_Disabilities:
['No' 'Yes']

Parental_Education_Level:
['College' 'High School' 'Postgraduate' nan]

Distance_from_Home:
['Far' 'Moderate' 'Near' nan]

Gender:
['Female' 'Male']

In [73]:
for col in encoders:
    print(f"\n{col}:")
    print(list(encoders[col].classes_))

Parental_Involvement:
['High', 'Low', 'Medium']

Access_to_Resources:
['High', 'Low', 'Medium']

Extracurricular_Activities:
['No', 'Yes']

Motivation_Level:
['High', 'Low', 'Medium']

Internet_Access:
['No', 'Yes']

Family_Income:
['High', 'Low', 'Medium']

Teacher_Quality:
['High', 'Low', 'Medium', nan]

School_Type:
['Private', 'Public']

Peer_Influence:
['Negative', 'Neutral', 'Positive']

Learning_Disabilities:
['No', 'Yes']

Parental_Education_Level:
['College', 'High School', 'Postgraduate', nan]

Distance_from_Home:
['Far', 'Moderate', 'Near', nan]

Gender:
['Female', 'Male']